### PR TITLE
KZL-834 Fixed sorting in raw JSON searches

### LINKED ISSUE #481: Unable to sort results using Raw JSON search
In the Raw JSON query panel, I type the following query

```JSON
{
  "query": {
    "bool": {
      "must": {
        "match_phrase_prefix": {
          "job": "National"
        }
      }
    }
  },
  "sort": {
    "lastName": "asc"
  }
}
```

## Expected Behavior
The results should be sorted by `lastName` ascending.

## Current Behavior
The results are not sorted.

## Context (Environment)
Kuzzle Admin Console 2.2.3

### PR DESCRIPTION
**Pull request by xbill82**
## What does this PR do ?
Fixes #481 

### How should this be manually tested?

See the issue

### Other changes
Renamed `filterManager::formatSort` to `toSort`

### CODE REVIEW

File: src/components/Data/Documents/Page.vue [hunk 1]
```diff
@@ -435,15 +435,13 @@ export default {
 
       let searchQuery = null
       searchQuery = filterManager.toSearchQuery(this.currentFilter)
+      console.log(searchQuery)
```
Comment (scottinet) [inline src/components/Data/Documents/Page.vue]: debug leftover?

File: src/components/Data/Documents/Page.vue [hunk 2]
```diff
@@ -435,15 +435,13 @@ export default {
...
         searchQuery = {}
       }
 
-      let sorting = ['_uid'] // by default, sort on uid: prevent random order
-      if (this.currentFilter.sorting) {
-        sorting = filterManager.formatSort(this.currentFilter.sorting)
-      }
-
+      const sorting = filterManager.toSort(this.currentFilter)
+      console.log(sorting)
```
Comment (scottinet) [inline src/components/Data/Documents/Page.vue]: debug leftover?
