### PR TITLE
Fix overlapping checkboxes

### LINKED ISSUE #551: Checkbox UI is conflicting on Security edition
Screenshot 2019-06-26 at 11 52 41

As you can see, with booleans, it overlap on others fields.

Mapping

```json
{
  "actCle": {
    "type": "long"
  },
  "birthDate": {
    "type": "date"
  },
  "connectedAsAnAthlete": {
    "type": "boolean"
  },
  "disciplineId": {
    "type": "long"
  },
  "disciplineName": {
    "type": "text",
    "fields": {
      "keyword": {
        "type": "keyword",
        "ignore_above": 256
      }
    }
  },
  "email": {
    "type": "text",
    "fields": {
      "keyword": {
        "type": "keyword",
        "ignore_above": 256
      }
    }
  },
  "firstName": {
    "type": "text",
    "fields": {
      "keyword": {
        "type": "keyword",
        "ignore_above": 256
      }
    }
  },
  "gymSante": {
    "type": "boolean"
  },
  "id": {
    "type": "long"
  },
  "lastName": {
    "type": "text",
    "fields": {
      "keyword": {
        "type": "keyword",
        "ignore_above": 256
      }
    }
  },
  "licenceKeyNumber": {
    "type": "text",
    "fields": {
      "keyword": {
        "type": "keyword",
        "ignore_above": 256
      }
    }
  },
  "login": {
    "type": "text",
    "fields": {
      "keyword": {
        "type": "keyword",
        "ignore_above": 256
      }
    }
  },
  "mobilePhoneNumber": {
    "type": "text",
    "fields": {
      "keyword": {
        "type": "keyword",
        "ignore_above": 256
      }
    }
  },
  "name": {
    "type": "text",
    "fields": {
      "keyword": {
        "type": "keyword",
        "ignore_above": 256
      }
    }
  },
  "niveau": {
    "type": "text",
    "fields": {
      "keyword": {
        "type": "keyword",
        "ignore_above": 256
      }
    }
  }
}
```

### PR DESCRIPTION
**Pull request by jenow**
## What does this PR do ?

fix #551 #565

### CODE REVIEW

File: src/components/Common/JsonForm/JsonFormItemCheckbox.vue [hunk 1]
```diff
@@ -50,3 +50,9 @@ export default {
   }
 }
 </script>
+
+<style scoped>
+.JsonFormItemCheckbox {
+  position: relative !important;
```
Comment (Yoann-Abbes) [inline src/components/Common/JsonForm/JsonFormItemCheckbox.vue]: :1st_place_medal:
