### PR TITLE
fix bug delete history search

### LINKED ISSUE #877: Deleting searches from history doesn't work
## Expected Behavior
Deleting searches from the History tab deletes them definitely.

## Current Behavior
If, after deleting all the searches, you go to another tab (e.g. Raw JSON) and then back to History, the searches are still present.

## Steps to Reproduce
delete-search-history-bug

## Context (Environment)

Kuzzle version: 2.8
Node.js version: 12
Admin Console Version: 4

### PR DESCRIPTION
**Pull request by berthieresteban**
fix #877

### CODE REVIEW

**Review by xbill82 — APPROVED** [review]

File: src/components/Common/Filters/FilterHistoryItem.vue [hunk 1]
```diff
@@ -46,6 +46,7 @@
             <b-button
               variant="link"
               @click="deleteFilter"
+              :data-cy="'FilterHistoryItem-deleteBtn--' + id"
```
Comment (Njuelle) [inline src/components/Common/Filters/FilterHistoryItem.vue:49]:
```suggestion
              :data-cy="`FilterHistoryItem-deleteBtn--${id}`"
```

File: test/e2e/cypress/integration/single-backend/search.spec.js [hunk 2]
```diff
@@ -702,6 +702,35 @@ describe('Search', function() {
     }
   })
 
+  it.only('Should be able to delete a previous searche in the search history.', () => {
```
Comment (Njuelle) [inline test/e2e/cypress/integration/single-backend/search.spec.js:705]:
```suggestion
  it('Should be able to delete a previous search in the search history', () => {
```

**Review by Njuelle — CHANGES_REQUESTED** [review]

File: test/e2e/cypress/integration/single-backend/search.spec.js (hunk 2 above)
Comment (berthieresteban) [reply test/e2e/cypress/integration/single-backend/search.spec.js:705]: Damn, you figured it out

**Review by Njuelle — APPROVED** [review]
