### PR TITLE
Fix Json-editor multiple instance

### LINKED ISSUE #893: [bug] Cannot use form-view with multiple instances of JsonFormInput
Cannot use form-view with multiple instances of JsonFormInput

### PR DESCRIPTION
**Pull request by Njuelle**
## What does this PR do ?
Fix #893  Json-editor multiple instance

### How should this be manually tested?
  - Step 1 : Create a collection with at least 2 nested properties
```
{
  "bar": {
    "properties": {
      "barfoo": {
        "type": "keyword"
      },
      "bazfoo": {
        "type": "keyword"
      }
    }
  },
  "foo": {
    "properties": {
      "foobar": {
        "type": "keyword"
      },
      "foobaz": {
        "type": "keyword"
      }
    }
  }
}
```
  - Step 2 : try create and edit a document with the form-view enabled

### CODE REVIEW

File: src/components/Common/JsonEditor.vue [hunk 1]
```diff
@@ -26,70 +27,77 @@
...
       type: String,
       default: ''
     },
     readonly: Boolean,
-    id: String,
     height: { type: Number, default: 250 }
   },
+  data() {
+    return {
+      editor: null
```
Comment (xbill82) [inline src/components/Common/JsonEditor.vue:49]: What is the purpose of putting the `editor` variable in the component state?

**Review by xbill82 — COMMENTED** [review]
It would be nice if we had the same code-formatting rules.

File: src/components/Common/JsonEditor.vue (hunk 1 above)
Comment (Njuelle) [reply src/components/Common/JsonEditor.vue:49]: it is necessary to have the `editor` variable scoped to the component to be able to use several instances

**Review by jenow — APPROVED** [review]

File: src/components/Common/JsonEditor.vue (hunk 1 above)
Comment (xbill82) [reply src/components/Common/JsonEditor.vue:49]: why?

File: test/e2e/cypress/integration/single-backend/formView.spec.js [hunk 2]
```diff
@@ -38,6 +44,10 @@ describe('Form view', function() {
           phone: 'Blackberry',
           car: 'Laguna'
         },
+        skill: {
+          name: 'managment',
+          level: '1'
+        },
         job: 'Always asking Esteban to do his job',
         employeeOfTheMonthSince: '1996-07-10'
       }
```
Comment (berthieresteban) [inline test/e2e/cypress/integration/single-backend/formView.spec.js:53]: :heart:

File: src/components/Common/JsonEditor.vue (hunk 1 above)
Comment (berthieresteban) [reply src/components/Common/JsonEditor.vue:49]: If we let the `editor` in global, if we add multiple json-editors there will still be only one `editor` variable wich will be overrided each time we instanciate a new json-editor.
So call setContent method of a json-editor component will always set the content on the last instanciated editor no matter wich json-editor's method we call

Comment (xbill82) [reply src/components/Common/JsonEditor.vue:49]: I see. The `editor` variable is scoped to the JSONEditor.vue module, which is a singleton, in the CommonJS modules model. The module exports a VueJS Component config, which is passed to the `Vue` constructor each time this component is instantiated. But this config has a reference to the `editor` variable, which is actually overwritten, as you rightly say, each time the component is instantiated. By putting the variable inside the `data` structure, you make it local to the component instead, which is obviously not a singleton. This is a nice thing to keep in mind for future developments.

I still don't like the idea of putting a complex object (i.e. one that has attributes and functions) inside the `data` structure, because it is meant to keep track of the _state_ of the component, yet this object is just logic to make the editor work. We should find a way to replicate this reference each time the component is created, and avoid the reference to be overwritten.

I am not really hurried to ship this fix, but if you are, we can keep this enhancement for later. What do you think?

Comment (berthieresteban) [reply src/components/Common/JsonEditor.vue:49]: After merge this PR I'll create an issue concerning the refacto of the json-editor and we'll probably need a workshop

**Review by berthieresteban — APPROVED** [review]
