### PR TITLE
Vertical layout improvements

### LINKED ISSUE #774: Textarea for editing document is too short and mapping is automatically unfolded
Being able to edit more than 15 rows of content

## Current Behavior

Small textarea and veryyy long page with the mapping

## Possible Solution

Let the mapping folded and unfoldable + let the user adjust (and save  the setting?) the textarea if possible

## Steps to Reproduce

1.
2.
3.
4.

## Context (Environment)

Kuzzle version:
Node.js version:
Admin Console Version:

### PR DESCRIPTION
**Pull request by xbill82**
## What does this PR do ?
Fixes #774 by allowing the JSON editor and the column on the right to take all the available height but not more. This improvement has been applied to all the forms that contain a JSON editor.

output

### How should this be manually tested?
Open one of the following forms
* Create/Update document
* Create/Update collection
* Create/Update role
* Create/Update profile
* Edit user custom mapping
and resize your window vertically.

### CODE REVIEW

File: src/components/Security/Profiles/CreateOrUpdate.vue [hunk 1]
```diff
@@ -97,6 +100,27 @@
   </b-card>
 </template>
 
+<style lang="scss" scoped>
+.ProfileCreateOrUpdate {
+  // margin-bottom: 3em;
```
Comment (Njuelle) [inline src/components/Security/Profiles/CreateOrUpdate.vue:105]:
```suggestion
```

File: src/components/Security/Profiles/Update.vue [hunk 2]
```diff
@@ -14,13 +14,21 @@
   </b-container>
 </template>
 
+<style lang="scss" scoped>
```
Comment (Njuelle) [inline src/components/Security/Profiles/Update.vue:17]: IMHO we can use Bootstrap classes: `d-flex flex-column h-100`
Let's keep the custom classes for when we really can't do without

File: src/components/Security/Roles/CreateOrUpdate.vue [hunk 3]
```diff
@@ -97,6 +99,28 @@
   </b-container>
 </template>
 
+<style lang="scss" scoped>
```
Comment (Njuelle) [inline src/components/Security/Roles/CreateOrUpdate.vue:102]: Styles duplicated with that of the `profiles/createOrUpdate` component.
Though I don't know if it's a good thing to refactor it here and now

File: src/components/Security/Users/EditCustomMapping.vue [hunk 4]
```diff
@@ -83,11 +75,19 @@
           </div>
         </template>
       </b-card>
-    </div>
+    </template>
   </b-container>
 </template>
 
 <style lang="scss" scoped>
+.EditUserMapping {
```
Comment (Njuelle) [inline src/components/Security/Users/EditCustomMapping.vue:83]: Also use bootstrap classes here
